### ISSUE TITLE
add subdivx.com as repo for latine people

### ISSUE THREAD

**Issue by skypce** [Diaoul/subliminal#502] opened 2015-09-06 22:12 UTC
Will be great if in your app features add subdivx.com as subtitle source too. Best regards.

**Comment by Diaoul** [comment] 2015-09-07 11:07
Duplicate of #279

**Closed by Diaoul** 2015-09-07 11:07 UTC

**Comment by nMaib0** [comment] 2016-09-02 12:49
Hello, is there a possibility this could get made? Honestly, without a subdivx plugin subliminal is basically useless for latin people. SubDivx has hundreds of people actively uploading subtitles that exist only on that site.
