### ISSUE TITLE
Add framerate to video class

### ISSUE THREAD

**Issue by MoshiMoshi0** [Diaoul/subliminal#835] opened 2017-11-18 15:19 UTC
I think we should have framerate field in video class that could be used for matching subtitles. 
The metadata refiner should already have it from enzyme, but i've read that matroska header might report wrong framerate. 
So maybe we could have mediainfo refiner using pymediainfo? That would also solve the issue with enzyme supporting only mkv.

What do you think?

**Comment by getzze** [comment] 2024-06-14 13:10
Duplicate of #748

**Closed by getzze** 2024-06-14 13:10 UTC
Labels: type/enhancement
