### ISSUE TITLE
 Issue arises after trying to download subtitles

### ISSUE THREAD

**Issue by bkemmer** [Diaoul/subliminal#928] opened 2018-07-12 19:11 UTC
Trying to run subliminal, I faced this output:

```
Downloading subtitles  [#################################---]   94%  0d 00:03:13  Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv                                  
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 69, in guessit
    return default_api.guessit(string, options)
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 182, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=Mr.Robot.S03E05.WEB-DL.WEB-Rip
options={'type': 'episode'}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/guessit/api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/usr/local/lib/python2.7/dist-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/usr/local/lib/python2.7/dist-packages/guessit/rules/processors.py", line 220, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
```
As it was written I opened an issue in guessit github, but trying to make this request by my own I found that the problem is that the wrong string are been sent to guessit:

```
python __main__.py "Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv"
For: Mr.Robot.S03E05.eps3.4_runtime-error.r00.WEBDL-1080p.mkv
GuessIt found: {
    "title": "Mr Robot", 
    "season": 3, 
    "episode": 5, 
    "episode_title": "eps3 4 runtime-error r00", 
    "source": "Web", 
    "screen_size": "1080p", 
    "container": "mkv", 
    "mimetype": "video/x-matroska", 
    "type": "episode"
}

python __main__.py "Mr.Robot.S03E05.WEB-DL.WEB-Rip"
For: Mr.Robot.S03E05.WEB-DL.WEB-Rip
Traceback (most recent call last):
  File "__main__.py", line 170, in <module>
    main()
  File "__main__.py", line 163, in main
    guess_filename(filename, options)
  File "__main__.py", line 42, in guess_filename
    guess = api.guessit(filename, options)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/guessit/api.py", line 69, in guessit
    return default_api.guessit(string, options)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/guessit/api.py", line 182, in guessit
    raise GuessitException(string, options)
guessit.api.GuessitException: An internal error has occured in guessit.
===================== Guessit Exception Report =====================
version=3.0.0
string=Mr.Robot.S03E05.WEB-DL.WEB-Rip
options={'allowed_languages': ['de', 'en', 'es', 'ca', 'cs', 'fr', 'he', 'hi', 'hu', 'it', 'ja', 'ko', 'nl', 'pl', 'pt', 'ro', 'ru', 'sv', 'te', 'uk', 'mul', 'und'], 'expected_title': ['OSS 117'], 'allowed_countries': ['au', 'us', 'gb'], 'filename': ['Mr.Robot.S03E05.WEB-DL.WEB-Rip']}
--------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bkemmer/.local/lib/python2.7/site-packages/guessit/api.py", line 170, in guessit
    matches = self.rebulk.matches(string, options)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/rebulk/rebulk.py", line 288, in matches
    self._execute_rules(matches, context)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/rebulk/rebulk.py", line 319, in _execute_rules
    rules.execute_all_rules(matches, context)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/rebulk/rules.py", line 318, in execute_all_rules
    when_response = execute_rule(rule, matches, context)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/rebulk/rules.py", line 343, in execute_rule
    rule.then(matches, when_response, context)
  File "/home/bkemmer/.local/lib/python2.7/site-packages/guessit/rules/processors.py", line 220, in then
    if match.raw[0] in seps_no_groups and (len(match.raw) < 3 or match.raw[2] not in seps_no_groups):
IndexError: string index out of range
--------------------------------------------------------------------
Please report at https://github.com/guessit-io/guessit/issues.
====================================================================

```

**Comment by bkemmer** [comment] 2018-07-13 18:20
Is unrar required to use legendastv provider? I found this error in --debug mode:

```
DEBUG:subliminal.providers.legendastv:Identified rar archive
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 440, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 400, in query
    self.download_archive(a)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/legendastv.py", line 331, in download_archive
    archive.content = RarFile(archive_stream)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 666, in __init__
    self._parse()
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 858, in _parse
    self._file_parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 973, in parse
    self._parse_real()
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 1047, in _parse_real
    self.process_entry(fd, h)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 1460, in process_entry
    cmt = self._read_comment_v3(item, self._password)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 1414, in _read_comment_v3
    inf.file_size, inf.flags, inf.CRC, psw, inf.salt)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 2747, in rar3_decompress
    p = custom_popen(cmd)
  File "/usr/local/lib/python2.7/dist-packages/rarfile.py", line 2816, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
INFO:subliminal.core:Discarding provider legendastv
```
full log attached
[subliminal-debug.log](https://github.com/Diaoul/subliminal/files/2193753/subliminal-debug.log)

**Comment by duramato** [comment] 2018-07-13 18:22
Yes, it is required AFAIK @bkemmer

**Comment by bkemmer** [comment] 2018-07-14 01:16
Solved the rar problem but still the same error!

[subliminal-debug2.log](https://github.com/Diaoul/subliminal/files/2194544/subliminal-debug2.log)

**Comment by alanaasmaa** [comment] 2018-08-20 17:04
Check if my suggested alias works on #933

**Comment by ratoaq2** [comment] 2019-02-17 18:13
Closing this since it's a duplicate of #933 
But can you still confirm that's not an issue anymore with latest guessit 3.0.3 ?

**Closed by ratoaq2** 2019-02-17 18:13 UTC
