### ISSUE TITLE
Unicode handling errors

### ISSUE THREAD

**Issue by ieno** [Diaoul/subliminal#527] opened 2015-10-16 14:52 UTC
When parsing filenames containing the 'ñ' (byte 0xc3) or '…' (byte 0xe2) character, subliminal (1.0.1) on my Debian 8.2 box errors out:
```
ERROR:subliminal.cli:Unexpected error while collecting directory path /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 208, in download
    scanned_videos = scan_videos(p, subtitles=not force, embedded_subtitles=not force)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 415, in scan_videos
    for dirpath, dirnames, filenames in os.walk(path):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

**Comment by Diaoul** [comment] 2015-10-16 15:43
I will try to reproduce and let you know.

**Comment by Diaoul** [comment] 2015-10-30 09:28
I cannot reproduce this.
```
$ mkdir test
$ touch test/Mañana.S01E02.The.Fix.Is.Coming-[SUB].mkv
$ subliminal download -l en test
Collecting videos  [####################################]  100%      
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%                                            
Downloaded 1 subtitle
```

**Comment by Diaoul** [comment] 2015-11-05 22:43
Any updates on this? Can you give more precise reproduce steps?

**Comment by ieno** [comment] 2015-11-08 16:36
Hm, strange...this is what happens on my machine when doing the same thing:

```
# subliminal --version
subliminal, version 1.0.1
# python --version
Python 2.7.9
# cat /etc/debian_version
8.2
# mkdir test
# touch test/Mañana.S01E02.The.Fix.Is.Coming-[SUB].mkv
# subliminal --debug download -l en test
Collecting videos  [####################################]  100%  testDEBUG:subliminal.cli:Collecting path test
ERROR:subliminal.cli:Unexpected error while collecting directory path test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 208, in download
    scanned_videos = scan_videos(p, subtitles=not force, embedded_subtitles=not force)
  File "/usr/local/lib/python2.7/dist-packages/subliminal/video.py", line 415, in scan_videos
    for dirpath, dirnames, filenames in os.walk(path):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
Collecting videos  [####################################]  100%
0 video collected / 0 video ignored / 1 error
```
Tried in bash/sh, same result...not sure what more information I can give you.

**Comment by Diaoul** [comment] 2015-11-08 16:42
Can you try to run the same using python 3? Is `ñ` a valid char for your current locale?

**Comment by ieno** [comment] 2015-11-08 18:08
Ah, locale was defaulted to POSIX. After changing it to an UTF-8 compliant one, the error's gone.

**Comment by Diaoul** [comment] 2015-11-21 11:06
Let's close this then.

**Closed by Diaoul** 2015-11-21 11:06 UTC
Labels: status/cannot-reproduce, type/bug
