### ISSUE TITLE
test_legendastv.py: test_login_bad_password: Failed: DID NOT RAISE (AuthenticationError)

### ISSUE THREAD

**Issue by Coacher** [Diaoul/subliminal#667] opened 2016-05-29 01:27 UTC
Hello.

One test failure with subliminal from develop @ e2331bef2c827406f92b1696b96241137163fe4f.

Same error with Python 2.7 and 3.4:
```
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.4.3, pytest-2.8.7, py-1.4.30, pluggy-0.3.1
rootdir: /var/tmp/portage/media-video/subliminal-9999/work/subliminal-9999, inifile: pytest.ini
plugins: cov-1.8.1
collected 326 items

HISTORY.rst s
README.rst s
docs/index.rst s
docs/api/cache.rst s
docs/api/cli.rst s
docs/api/core.rst s
docs/api/exceptions.rst s
docs/api/extensions.rst s
docs/api/providers.rst s
docs/api/refiners.rst s
docs/api/score.rst s
docs/api/subtitle.rst s
docs/api/utils.rst s
docs/api/video.rst s
docs/user/cli.rst s
docs/user/how_it_works.rst s
docs/user/provider_guide.rst s
docs/user/usage.rst .
tests/test_addic7ed.py .........................................
tests/test_core.py .......................................
tests/test_extensions.py .....
tests/test_legendastv.py .........F................
tests/test_napiprojekt.py .....
tests/test_omdb.py ...............
tests/test_opensubtitles.py .........................
tests/test_podnapisi.py .........
tests/test_provider.py ........
tests/test_score.py .......
tests/test_shooter.py .........
tests/test_subscenter.py ................
tests/test_subtitle.py ................
tests/test_thesubdb.py ...........
tests/test_tvdb.py ................................
tests/test_tvsubtitles.py ........................
tests/test_utils.py .....
tests/test_video.py ...............

==================================================================================== FAILURES =====================================================================================
_____________________________________________________________________________ test_login_bad_password _____________________________________________________________________________

    @pytest.mark.integration
    @vcr.use_cassette
    def test_login_bad_password():
        provider = LegendasTVProvider(USERNAME, 'wrong')
        with pytest.raises(AuthenticationError):
>           provider.initialize()
E           Failed: DID NOT RAISE

tests/test_legendastv.py:87: Failed
=============================================================== 1 failed, 308 passed, 17 skipped in 1376.71 seconds ===============================================================
```

This is not reproducible with subliminal-2.0-rc1, thus it's a regression.

Please fix.

**Comment by Diaoul** [comment] 2016-05-29 15:25
Travis build is passing, that's weird.

**Comment by Coacher** [comment] 2016-05-29 16:33
If I can help you further to resolve this, please let me know.

**Comment by Diaoul** [comment] 2016-06-04 18:38
Sorry I cannot reproduce this either.

**Comment by Coacher** [comment] 2016-06-04 19:37
I narrowed the problem to this function call:
`soup.find('div', {'class': 'alert-error'}, string=re.compile(u'Usuário ou senha inválidos'))`
It doesn't return anything when it should.
If I drop the whole `string=...` part, I can see that required div is found.
If I change the `string=` to `text=` as it was before 08fbe4b, then I also can see that required div is found.
Could it be that we have different versions of some python module that messes things up?
Or am I missing something?
Here's my python session:
```
$ python
Python 3.4.3 (default, Feb 22 2016, 01:47:43) 
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> session = requests.Session()
>>> data = {'_method': 'POST', 'data[User][username]': 123, 'data[User][password]' : 456}
>>> r = session.post('http://legendas.tv/login', data, allow_redirects=False, timeout=10)
>>> from bs4 import BeautifulSoup
>>> soup = BeautifulSoup(r.content, 'html.parser')
>>> soup.find('div', {'class': 'alert-error'})
<div class="alert alert-error">
    Usuário ou senha inválidos</div>
>>> import re
>>> soup.find('div', {'class': 'alert-error'}, string=re.compile(u'Usuário ou senha inválidos'))
>>> soup.find('div', {'class': 'alert-error'}, string=re.compile('Usuário ou senha inválidos'))
>>> soup.find('div', {'class': 'alert-error'}, text=re.compile('Usuário ou senha inválidos'))
<div class="alert alert-error">
    Usuário ou senha inválidos</div>
>>> soup.find('div', {'class': 'alert-error'}, text=re.compile(u'Usuário ou senha inválidos'))
<div class="alert alert-error">
    Usuário ou senha inválidos</div>
```

**Comment by Coacher** [comment] 2016-06-04 19:40
I have dev-python/beautifulsoup-4.3.2 installed.
BS docs says 'string argument is new in Beautiful Soup 4.4.0. In earlier versions it was called text': https://www.crummy.com/software/BeautifulSoup/bs4/doc/#the-string-argument
subliminal setup.py says: beautifulsoup4>=4.2.0, so technically my bs version satisfies subliminal requirements, but you are actually using feature from future versions.

**Comment by Coacher** [comment] 2016-06-04 19:45
So the real problem here is that `string` argument for `soup.find` is only available in BS >= 4.4.0.
Please either update setup.py accordingly or use `text` instead.

**Comment by Coacher** [comment] 2016-06-04 19:52
Please note that string/text argument for soup.find is used inconsistently in legendastv.py:
https://github.com/Diaoul/subliminal/blob/master/subliminal/providers/legendastv.py#L185
https://github.com/Diaoul/subliminal/blob/master/subliminal/providers/legendastv.py#L306
These both should most likely be one way or the other.

**Comment by Coacher** [comment] 2016-06-06 07:48
Hello. The problem seems trivial, but annoying, Will PR speed things up?

**Comment by Diaoul** [comment] 2016-06-06 08:46
I'll fix this as soon I have some time, a PR shouldn't be necessary.

**Comment by Coacher** [comment] 2016-06-06 09:32
I'll wait patiently then.

**Comment by Diaoul** [comment] 2016-06-06 18:16
Fixed with 2.0.1

**Closed by Diaoul** 2016-06-06 18:16 UTC
Labels: type/bug

**Comment by Diaoul** [comment] 2016-06-06 18:20
I've chosen to update the requirements given that beautifulsoup 4.4.x is quite old now and due to the large number of bugfixes it brings.

Please let me know if that's a problem.

**Comment by Coacher** [comment] 2016-06-08 16:27
All tests pass successfully with 2.0.2 / develop @ 1c745c9.
Thank you very much.
