### ISSUE TITLE
[Resolved] MatchTree Error

### ISSUE THREAD

**Issue by MoonArrow** [Diaoul/subliminal#568] opened 2016-01-29 13:00 UTC
Hi,
I am using the last official version of Subliminal (v 1.1.1) on a 14.04 server. I get this error:

> Traceback (most recent call last):
>   File "/usr/local/bin/subliminal", line 11, in <module>
>     sys.exit(subliminal())
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
>     return f(get_current_context().obj, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 372, in download
>     hearing_impaired=hearing_impaired, only_one=single)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 184, in download_best_subtitles
>     for s in subtitles], key=operator.itemgetter(1), reverse=True)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 69, in get_matches
>     matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
>   File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 370, in guess_episode_info
>     return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 302, in guess_file_info
>     result.append(_guess_filename(filename, options, **kwargs))
>   File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 114, in _guess_filename
>     mtree = _build_filename_mtree(filename, options=options, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/__init__.py", line 127, in _build_filename_mtree
>     mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 120, in __init__
>     self._process(transformer, False)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 138, in _process
>     transformer.process(self.match_tree, self.options)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_release_group.py", line 223, in process
>     GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 227, in process_nodes
>     self.process_node(node)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 286, in process_node
>     self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matcher.py", line 241, in process_node
>     matcher_result = self.guess_func(string, node, self.options)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_release_group.py", line 175, in guess_release_group
>     if self.validate_node(leaf, node, True):
>   File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_release_group.py", line 143, in validate_node
>     if not self.validate_next_leaves(node):
>   File "/usr/local/lib/python2.7/dist-packages/guessit/transfo/guess_release_group.py", line 126, in validate_next_leaves
>     next_leaf = node.root.next_leaf(node)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matchtree.py", line 318, in next_leaf
>     return self._other_leaf(leaf, +1)
>   File "/usr/local/lib/python2.7/dist-packages/guessit/matchtree.py", line 322, in _other_leaf
>     index = leaves.index(leaf) + offset
> ValueError: \<MatchTree: root=.FR.W4F.FR.NoTAG\> is not in list

The command line looks like:
subliminal  --addic7ed "login" "passwd" --opensubtitles  "login2" "passwd2" download -l fr -l en --min-score 35  --encoding utf-8 -p opensubtitles -p addic7ed "/path/to/directory/"

Of course, directory exists, is readable and contains some videos (all MP4s). I must precise that some of the files names have very few/no information to guess what version could be applied. Like seriename.S02E03.mp4 and that's all, if it could help.

Obviously, the same command line is working for ages for tvshows and movies without a change. No special updates I can think of on the system.

Don't hesitate to ask me details or testing if needed.
M.

**Comment by Diaoul** [comment] 2016-01-29 14:19
Can you try the develop branch? I suspect a guessit 1.x issue, develop branch uses 2.x.
```
git clone -b develop https://github.com/Diaoul/subliminal.git
cd subliminal
python setup.py install
```

**Comment by MoonArrow** [comment] 2016-01-29 15:02
I install the develop branch (1.2.dev0). I got a new error:
> DEBUG:subliminal.cli:Collecting path /path/to/intermediate/
> DEBUG:subliminal.video:Walking directory /path/to/intermediate/
> ERROR:subliminal.cli:Unexpected error while collecting directory path /path/to/intermediate/
> Traceback (most recent call last):
>   File "build/bdist.linux-x86_64/egg/subliminal/cli.py", line 311, in download
>     subtitles_dir=directory, age=age)
>   File "build/bdist.linux-x86_64/egg/subliminal/video.py", line 446, in scan_videos
>     if datetime.utcnow() - datetime.utcfromtimestamp(os.path.getmtime(filepath)) > age:
> TypeError: can't compare datetime.timedelta to NoneType

Same command line used:
> subliminal --debug --addic7ed "login" "passwd" --opensubtitles "login2" "passwd2" download -l en -l fr --min-score 35 --encoding utf-8 -p opensubtitles -p addic7ed "/path/to/intermediate/"

M.

**Comment by MoonArrow** [comment] 2016-01-30 13:50
Hi,
For information, I checked the code today and I guessed that the problem was in fact that in my initial command line, no --age parameters, so the parameter was defaulted to None and making the difference comparison invalid (None is not anymore as a time difference valid expression).

Once I added a --age value to the commande line the develop branch does not issue the initial problem). So, please consider that issue has closed in 1.2.Develop but the age:None is an issue. Do you want me to open a separate issue for that ?

M.

**Comment by Diaoul** [comment] 2016-01-30 15:38
No need, I'll fix this soon.

**Comment by Toilal** [comment] 2016-01-30 20:55
Could you give me the value given to guessit, `self.movie_release_name` ? It would help to solve the issue in guessit 1.x which is still maintained ...

**Comment by MoonArrow** [comment] 2016-01-30 22:10
@Toilal If you provided me a way to provide the information, I will provide that information with pleasure

M.

**Comment by Toilal** [comment] 2016-01-30 22:11
The easiest is to add a print at the line where guessit function is called
(just before)

**Comment by MoonArrow** [comment] 2016-01-30 22:17
I am currently using the 1.2 develop version, is it still useful? I guess the 1.1 version (with the bug) is the one you are interested in ?

**Comment by Toilal** [comment] 2016-01-31 10:52
No you have to use latest released version of subliminal, that is still based on guessit 1.x version.

**Comment by Toilal** [comment] 2016-01-31 10:52
with develop version, I think you don't have this problem ? Right ?

**Comment by MoonArrow** [comment] 2016-01-31 11:35
What values do you want in the print and where ? I uninstall guessit and subliminal develop to reinstall the last release version.

**Comment by Toilal** [comment] 2016-01-31 11:43
In [providers/opensubtitles.py#L69](https://github.com/Diaoul/subliminal/blob/1.1.1/subliminal/providers/opensubtitles.py#L69), add this statement just before. (subliminal sources should be in `sites-package` directory of your python installation or virtualenv).

```python
print("guessit-input: " + self.movie_release_name)
```

or if running python 2
```python
print "guessit-input: " + self.movie_release_name
```

Then run subliminal in command line, and it should display the release name causing problem to guessit in console.

**Comment by MoonArrow** [comment] 2016-01-31 12:05
I get nothing. The code looks like:
>            # guess
>              print "guessit-input: " + self.movie_release_name
>            matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
The output is something like
> # /usr/local/bin/subliminal --addic7ed "user1" "passw1" --opensubtitles "user2" "pass2" download -l en -l fr --min-score 35 --encoding utf-8 -p opensubtitles -p addic7ed /path/to/intermediate/
> Collecting videos  [####################################]  100%
> 121 videos collected / 0 video ignored / 0 error
> Downloading subtitles  [------------------------------------]    2%  0d 00:03:19  Star.Wars.The.Clone.Wars.2008.S06E04.mp4
> Traceback (most recent call last):
>   File "/usr/local/bin/subliminal", line 11, in <module>
>     sys.exit(subliminal())
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
>    return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 27, in new_func
>     return f(get_current_context().obj, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/cli.py", line 372, in download
>    hearing_impaired=hearing_impaired, only_one=single)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 184, in download_best_subtitles
>     for s in subtitles], key=operator.itemgetter(1), reverse=True)
>   File "/usr/local/lib/python2.7/dist-packages/subliminal/providers/opensubtitles.py", line 70, in get_matches
>     matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
and then the rest of the trace as original issue.
No trace of the new print instruction... I checked the .pyc date has changed.

I can do others tests if needed.

**Comment by Toilal** [comment] 2016-01-31 12:18
Indent seems to be wrong, pull the print left of 2 spaces.

**Comment by MoonArrow** [comment] 2016-01-31 12:48
Damned me!!! Of course, the indent...

Well, I got that
> guessit-input: Star Wars The Clone Wars - 06x04 - Orders.W4F
> guessit-input: Star Wars The Clone Wars - 06x04 - Orders.WEBRip-2HD
> guessit-input:  Star.Wars.The.Clone.Wars.S06E04.Orders.720p.WEB-DL.x264.AAC
> guessit-input: Star.Wars.The.Clone.Wars.S06E04.1080p.BluRay.x264-FLHD
> guessit-input:  Star.Wars.The.Clone.Wars.S06E04.BDRIP.x264.Hun.Eng-Krissz
> guessit-input:  star.wars.the.clone.wars.s06e04.repack.webrip.x264-2hd
> guessit-input:  The.Clone.Wars.S06E04.720p.WEBRip.FR.W4F.FR.NoTAG

I think that the last line without star wars prefix could be the cause. Tell me if you need additional testing.

Thanks for support.

M.

**Comment by Toilal** [comment] 2016-01-31 13:08
Yes, thanks a lot ! I can reproduce the issue with `The.Clone.Wars.S06E04.720p.WEBRip.FR.W4F.FR.NoTAG.mkv` in guessit. 

It's also reported in guessit issue tracker, see guessit-io/guessit#260.

**Comment by MoonArrow** [comment] 2016-01-31 13:11
Happy to help.

I stay on that version for now if you want me to try something or a patch.

Regards,
M.

**Comment by Toilal** [comment] 2016-01-31 18:52
Fixed has been released in guessit `1.0.3`. Thanks for your contribution !

**Comment by MoonArrow** [comment] 2016-01-31 19:40
No problem. To let you know, I upgraded the subliminal package, resulting in guessit upgrade and I confirm that the issue disappeared.
Well done @Toilal :+1: 

Regards

**Comment by Diaoul** [comment] 2016-02-01 22:01
Thanks

**Closed by Diaoul** 2016-02-01 22:01 UTC
Labels: type/bug, type/dependency
