### ISSUE TITLE
No videos found

### ISSUE THREAD

**Issue by SeeDborg** [Diaoul/subliminal#470] opened 2015-07-22 10:02 UTC
I just installed version 1.0 on my raspberry pi and here is what I get :

subliminal download -l fr -s -v /media/RASPI-HDD2/Video/Series/

Collecting videos  [####################################]  100%
0 video collected / 0 video ignored

So it seems it does not find any videos ! It used to work with 0.7

**Comment by SeeDborg** [comment] 2015-07-22 10:04
When I try with --debug here is what I get for every TV shows directory :


ERROR:subliminal.video:Skipping badly encoded directory u'/media/RASPI-HDD2/Video/Series/Gotham'

**Comment by Diaoul** [comment] 2015-07-22 11:11
Can you try with python3?

**Comment by SeeDborg** [comment] 2015-07-22 11:53
tried it and now I have this everytime I launch subliminal :


Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 9, in <module>
    load_entry_point('subliminal==1.0', 'console_scripts', 'subliminal')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.2/dist-packages/subliminal-1.0-py3.2.egg/subliminal/cli.py", line 14, in <module>
    import click
  File "/usr/local/lib/python3.2/dist-packages/click/__init__.py", line 18, in <module>
    from .core import Context, BaseCommand, Command, MultiCommand, Group, \
  File "/usr/local/lib/python3.2/dist-packages/click/core.py", line 8, in <module>
    from .types import convert_type, IntRange, BOOL
  File "/usr/local/lib/python3.2/dist-packages/click/types.py", line 7, in <module>
    from .exceptions import BadParameter
  File "/usr/local/lib/python3.2/dist-packages/click/exceptions.py", line 2, in <module>
    from .utils import echo
  File "/usr/local/lib/python3.2/dist-packages/click/utils.py", line 301
    file.write(u'\n')
                   ^
SyntaxError: invalid syntax

**Comment by SeeDborg** [comment] 2015-07-22 12:05
>>> import os
>>> os.listdir('/media/RASPI-HDD2/Video/Series/')
['Jessica Jones', 'Aquarius (2015)', 'Arrow', 'Banshee', 'Battle Creek', 'Better Call Saul', 'Breaking Bad', 'Constantine', 'Continuum', 'Coupling', 'Coupling (US)', 'Daredevil', "DC's Legends of Tomorrow", 'Dragon Ball Kai', 'Fear The Walking Dead', 'Game of Thrones', 'Gotham', 'Heroes Reborn', 'House of Cards (US)', 'Humans', 'Iron Fist', 'Jonathan Strange & Mr Norrell', 'Kaamelot', 'Killjoys', 'Le Bureau des Légendes', 'Luke Cage', "Marvel's Agent Carter", "Marvel's Agents of S.H.I.E.L.D", 'Masters of Sex', 'Minority Report', 'Myster Mask', 'New Girl', 'Once Upon a Time (2011)', 'Penny Dreadful', 'Powers', 'Sense8', 'Sherlock', 'Star-Crossed', 'The Big Bang Theory', 'The Expanse', 'The Flash (2014)', 'The Leftovers', 'The Strain', 'The Walking Dead', 'True Blood', 'True Detective', 'Unbreakable Kimmy Schmidt', 'Vikings']
>>> os.listdir(u'/media/RASPI-HDD2/Video/Series/')
  File "<stdin>", line 1
    os.listdir(u'/media/RASPI-HDD2/Video/Series/')


for trying it with python3, i'm kind of a python noob, so tell me exactly what to do or leave me a few hours to figure it out ^^

**Comment by Neo00724** [comment] 2015-07-22 12:16
Same issue 

root@Serveur2ouf:~# subliminal --debug  download -l fr /media/10236d77-d0d5-49bf-834f-9e57c65fbff6/Series/Better\ Call\ Saul/Saison\ 1/
Collecting videos  [####################################]  100%  /media/10236d77-d0d5-49bf-834f-9e57c65fbff6/Series/Better Call Saul/Saison 1/ERROR:subliminal.video:Skipping badly encoded directory u'/media/10236d77-d0d5-49bf-834f-9e57c65fbff6/Series/Better Call Saul/Saison 1/'
ERROR:subliminal.video:Skipping badly encoded directory u'/media/10236d77-d0d5-49bf-834f-9e57c65fbff6/Series/Better Call Saul/Saison 1/.AppleDouble'

Maybe you have to skip the hidden folders ?

**Comment by Diaoul** [comment] 2015-07-22 12:38
This is done already, except it's done after the encoding check. If you can write a failing unittest that would be really helpful.
Right now I don't know if the issues comes from click passing a bytestring instead of a str or from os.walk returning a bytestring.

**Comment by Diaoul** [comment] 2015-07-22 15:38
Seems like this is due to both: http://click.pocoo.org/4/arguments/#file-path-arguments
It makes sense that click returns bytestring (on windows for example) so subliminal should handle it propertly.

**Comment by Diaoul** [comment] 2015-07-22 15:50
BTW no issue on python3

**Comment by Diaoul** [comment] 2015-07-22 17:46
Can you test if this is fixed on master?

**Comment by Neo00724** [comment] 2015-07-22 18:30
Fixed for me thank you

**Comment by Diaoul** [comment] 2015-07-22 18:36
I can reproduce this but there is no easy workaround. Working with bytestrings is leading to things like `filename.endswith('.mkv')` not working because if `filename` is bytestring and `'.mkv'` string (unicode) due to `from __future__ import unicode_literals` python will try to convert the former in unicode with ascii encoding which will fail.

Example:

    subliminal download -vv -l en Les\ Misérables\ \(2012\)/Les.Miserables.2012.1080p.Bluray.X264-BARC0DE.mkv

**Comment by Diaoul** [comment] 2015-07-22 18:40
Removing `from __future__ import unicode_literals` let python decide what is a string and what is not which leads to good results in both versions of python except it can have side effects everywhere else (logging, returned values, etc.).

I think it's safer to only work with unicode in python 2 and force conversion of paths right away in CLI.

**Comment by Diaoul** [comment] 2015-07-22 22:51
Fixed with 1.0.1

**Closed by Diaoul** 2015-07-22 22:51 UTC
Labels: bug
