### ISSUE TITLE
suggestion: use ctime to determine file age for filtering

### ISSUE THREAD

**Issue by ittayd** [Diaoul/subliminal#995] opened 2020-03-29 03:47 UTC
If someone moves files from one folder to the folder subliminal scans, their modification time doesn't change. Therefore the -a flag might cause subliminal to ignore them. It would be good to instead or in addition use ctime.

**Comment by getzze** [comment] 2024-06-14 13:14
Duplicate of #860

**Closed by getzze** 2024-06-14 13:14 UTC
Labels: type/enhancement
