### ISSUE TITLE
Unexpected error in provider "opensubtitles"

### ISSUE THREAD

**Issue by Rwanou88** [Diaoul/subliminal#904] opened 2018-03-26 12:33 UTC
**Soft/Branch/Commit:**
SickBeard Custom / master / `d6eb72d4e1019e5d1286ae6ac1d7e4b318229ebe`
**OS:**
Linux-4.4.15+-x86_64-with-glibc2.2.5
**What you did:**
Automatic search
**What happened:**
I had this error
**What you expected:**
Subs search on this provider

**Logs:**
```
2018-03-24 22:04:09 WARNING  FINDSUBTITLES :: [d6eb72d] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 194, in query
    language = Language.fromopensubtitles(subtitle_item['SubLanguageID'])
TypeError: string indices must be integers, not str
2018-03-24 19:04:43 WARNING  FINDSUBTITLES :: [d6eb72d] Unexpected error in provider u'opensubtitles'
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 228, in list_subtitles
    query=query, season=season, episode=episode, tag=os.path.basename(video.name))
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/subliminal/providers/opensubtitles.py", line 194, in query
    language = Language.fromopensubtitles(subtitle_item['SubLanguageID'])
TypeError: string indices must be integers, not str
```

**Comment by h3llrais3r** [comment] 2018-03-26 18:28
Duplicate of https://github.com/Diaoul/subliminal/issues/902 which should have been fixed.
Please delete the subliminal cache file before retrying.

**Closed** 2019-02-17 18:52 UTC
Labels: type/bug
