### ISSUE TITLE
Windows Python 2.7 path error

### ISSUE THREAD

**Issue by labrys** [Diaoul/subliminal#653] opened 2016-04-25 17:32 UTC
##### Summary:
Using python 2.7 and Subliminal 2.0rc1 on Windows causes either a path error if passed a non-unicode path or a Unicode error if passed unicode.

##### Minimum steps to reproduce:
Use the library code from https://github.com/Diaoul/subliminal, enable logging, and change the `'/video/folder'` to a path containing a unicode character such as `ō`.
```python
Traceback (most recent call last):
  File "C:/src/indexer/testsubs.py", line 17, in <module>
    videos = [v for v in scan_videos('G:\\Shōws') if v.age < timedelta(weeks=2)]
  File "build\bdist.win-amd64\egg\subliminal\core.py", line 458, in scan_videos
ValueError: Path does not exist
```
With unicode path:
```python
DEBUG:rebulk.rules:Checking rule condition: <TitleFromPosition>
Traceback (most recent call last):
  File "C:\Python27x64\lib\logging\__init__.py", line 853, in emit
    msg = self.format(record)
  File "C:\Python27x64\lib\logging\__init__.py", line 726, in format
    return fmt.format(record)
  File "C:\Python27x64\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27x64\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "C:\Python27x64\lib\site-packages\rebulk\match.py", line 781, in __repr__
    return "<%s:%s%s%s%s%s>" % (self.value, self.span, flags, name, tags, defined)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5: ordinal not in range(128)
```

This works just fine using Python 3.

**Comment by Diaoul** [comment] 2016-04-26 07:59
Thanks for the very detailed report, I reported the second issue upstream to rebulk (https://github.com/Toilal/rebulk/issues/3)

As for the first one, the path is tested using `os.path.exists` so make sure you pass bytes encoded with the proper encoding (same as your filesystem, CP1252 I guess).
I guessed you saved your script file as utf-8 so the encoding of `'G:\\Shōws'` is utf-8. Try saving your file as CP1252.

A cleaner solution would be to work with unicode paths and encode them with your file system encoding when using it.
```python
path = u'G:\\Shōws'
videos = [v for v in scan_videos(path.encode('cp1252')) if v.age < timedelta(weeks=2)]
```
An even cleaner solution would be to work only with unicode paths and never encode them but it doesn't work due to a bug as you reported.

**Comment by labrys** [comment] 2016-04-26 11:20
@Diaoul The problem is on windows the console uses `cp1252` (or other relevant Windows encoding depending on user settings), but the actual path on Windows is stored as unicode.  For example in Windows console `G:\Shōws` is actually displayed as `G:\Shows` and in explorer it shows correctly as `G:\Shōws`.  (More specifically Windows uses `utf-16-le` for NTFS, but the standard libraries work with the path as unicode)

Using `cp1252`, `ascii`, `utf-16-le` (the "actual" Windows encoding), or any other relevant encoding `os.path.exists` returns false.  Using unicode `os.path.exists` returns true.

The most reliable way on Windows would be to use unicode.  The only other option I'm aware of would be to use the "short" path name (e.g. `os.path.exists('G:\SHWS~1')` returns True).  The problem with the short path name is it requires importing the win32api to get it and it mangles the name, which subliminal needs to determine the desired subtitle.  

In addition passing the short file path causes other issues.  For example `scan_videos` uses `os.path.walk` which doesn't work properly with unicode contents on Windows unless the path passed to it is unicode.  So when you build `filepath` (`core.py` L486) it joins the short filename with the console representation of the video file (e.g. `cp1252`) causing `ValueError: Path does not exist` for contents with unicode in the names.

I'm not sure if these are the only issues caused by this, but it should at least give you some ammunition to approach this.

**Comment by labrys** [comment] 2016-04-27 07:25
Oh I forgot to add that using `mbcs` for encoding type also doesn't work.

**Comment by Toilal** [comment] 2016-04-27 21:38
I've configured the whole environment on Windows to fix the guessit part of the issue. It seems OK now, i'll commit and release soon.

But I still have an error related to legendastv provider:

```
ERROR:subliminal.core:Unexpected error in provider 'legendastv'
Traceback (most recent call last):
  File "C:\idea-projects\subliminal\subliminal\core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\idea-projects\subliminal\subliminal\providers\legendastv.py", line 408, in list_subtitles
    return [s for l in languages for s in self.query(l, title, season=season, episode=episode, year=video.year)]
  File "C:\idea-projects\subliminal\subliminal\providers\legendastv.py", line 312, in query
    titles = self.search_titles(sanitize(title))
  File "C:\Python\27-subliminal\lib\site-packages\dogpile\cache\region.py", line 1045, in decorate
    key = key_generator(*arg, **kw)
  File "C:\Python\27-subliminal\lib\site-packages\dogpile\cache\util.py", line 84, in generate_key
    return namespace + "|" + " ".join(map(to_str, args))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 1: ordinal not in range(128)
```

I'm running the README script too, in a folder named ```C:\Shöws``` containing a dummy movie named ```töst.mkv```.

**Comment by Diaoul** [comment] 2016-04-30 09:34
Seems it's related to python2: https://bitbucket.org/zzzeek/dogpile.cache/issues/94/unicode-support-in-function_key_generator
Here is the relevant documentation: https://dogpilecache.readthedocs.io/en/latest/api.html#dogpile.cache.region.CacheRegion.cache_on_arguments.params.to_str

**Comment by Diaoul** [comment] 2016-04-30 09:36
This is not a bug (yet) as this is due to a hypothetical series name with non-ascii characters searched on Addic7ed provider. I'd rather fix this with an actual real use case.

**Comment by Diaoul** [comment] 2016-04-30 10:17
I've tried to fix this but a bunch of other issues happen when dealing with non-ascii series name and none of them are easy to fix.
I suggest moving to python 3 if encoding is a real issue.

**Comment by labrys** [comment] 2016-04-30 19:20
@Diaoul Actually its reproducible with any series having a non-ascii name.  This started with a user unable to search the series `Sekkō Boys`.  Also while moving Medusa to python 3 is in progress, we still have to support python 2 on devices which may not have python 3 available such as some NAS's.

**Comment by Diaoul** [comment] 2016-04-30 21:51
Well, I'm not gonna fix python2 :)
I'll do my best as long as it stays non-intrusive but I won't invest too much effort into this given that python3 is a future-proof solution.

Please open a separate issue as this one is solved so we can keep things clear.

@Toilal: please tell me when you make a new release

**Comment by Toilal** [comment] 2016-05-01 12:49
Rebulk has been released, so user only have to perform a ```pip install --upgrade``` to upgrade rebulk.

**Closed** 2016-05-01 16:23 UTC
Labels: type/dependency
