### ISSUE TITLE
Inforequest: requirements versions?

### ISSUE THREAD

**Issue by h3llrais3r** [Diaoul/subliminal#465] opened 2015-07-16 13:21 UTC
What are the versions of the different requirements?
Previously, the versions were specified in the the requirements.txt.
Now it's only the dependencies in the setup.py.

It would be nice to have a version of all the requirements for which it's working and tested.
I think this interesting for everyone who wants to use it as a library for another application and who wants to include all the dependencies in his own app.

**Comment by Diaoul** [comment] 2015-07-16 13:39
One needs to run the test suite with various versions of the libraries and establish the minimum required version for each library.

Help will be much appreciated on that.

**Comment by Diaoul** [comment] 2015-07-16 13:50
`requirements.txt` will not change though, I belive library should only define bounds for required versions of dependencies. The goal of `requirements.txt` is for applications to provide a fixed and reproducible dependency list.

**Comment by h3llrais3r** [comment] 2015-07-16 18:34
What are the versions that you have run your tests against?
So you are planning to put the requirements again in the requirements.txt or did I misunderstand what you are saying?

**Comment by h3llrais3r** [comment] 2015-07-16 20:46
Currently running tests with latest versions of requirements
```
guessit 0.10.3
babelfish 0.5.4
enzyme 0.4.1
beautifulsoup4 4.4.0
requests 2.7.0
click 4.1
dogpile.cache 0.5.6
stevedore 1.6.0
chardet 2.3.0
pysrt 1.0.1
six 1.9.0
```

**Comment by Diaoul** [comment] 2015-07-16 21:27
I'm running the tests against latest version of each library. For testing, I run `pip install -e .[test]`

I put back the entrypoints in setup.py because I now use stevedore for extension management and I did a fresh start. With wheels and virtualenvs being the norm, I think applications should move to this layout. [Flexget](https://github.com/Flexget/Flexget/) does that.

I'll see if I can extend the ExtensionManager to support manual registration.

**Comment by h3llrais3r** [comment] 2015-07-16 22:33
I can always register the entry points myself as workaround.
I did that in the previous version (before 0.8-dev) also. :)

I think I will to spend some time in checking those virtualenv stuff.

**Comment by Diaoul** [comment] 2015-07-17 07:35
I think I have a way to achieve this by subclassing stevedore's extension manager and overriding _find_entry_points to add my own. 

Shouldn't be too heavy and will probably make things easier for some developers.

I'll do that after I finished the user documentation and added doctests. Should be by Monday.

**Comment by Diaoul** [comment] 2015-07-19 18:53
Actually it seems a little weird to me to have two ways of loading providers. And only register language converters at runtime.
This is hacky and entry points were made to standardize that kind of things.

Did you have time to check virtualenv stuff? Is this missing feature a show stopper for 1.0 in your application?

**Comment by h3llrais3r** [comment] 2015-07-20 07:28
Sorry, I did not have the time yet to check.
Not blocking for my application, I can register the entrypoints myself when starting my application.
I also did this in version 0.7 of subliminal. ;)

**Comment by Diaoul** [comment] 2015-07-21 21:58
Fixed with 86c6d2c253d5700927c30acac040470759569b66

**Closed by Diaoul** 2015-07-21 21:58 UTC
Labels: status/help-wanted

**Comment by h3llrais3r** [comment] 2015-07-22 09:16
Thanks for updating!
I suppose everything has been tested with the minimum required libraries?
Or do you advise to use the latest versions as mentioned above?

**Comment by Diaoul** [comment] 2015-07-22 09:44
Well, I ran all the unittests successfully with those minimal requirements. For what it's worth.
I suggest using latest versions, usually new versions come out to fix bugs so that can't be a bad thing.

**Comment by Diaoul** [comment] 2015-07-22 09:44
1.0 is available on pypi and here: https://github.com/Diaoul/subliminal/releases

**Comment by h3llrais3r** [comment] 2015-07-22 13:14
Thanks! I already found your new version. :+1: 
I'm starting with the integration in my app now ;)
